import type { Action } from "./permissions";

export type Method = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
export type RouteRule = Action | "public" | "self" | "admin" | "setup";

/** Every registered route must appear here; the matrix test enforces it. */
export const ROUTE_ACTIONS: Record<`${Method} ${string}`, RouteRule> = {
  "GET /healthz": "public",
  "POST /api/auth/login": "public",
  "POST /api/auth/logout": "self",
  "GET /api/me": "self",
  "POST /api/me/password": "self",
  "GET /api/setup": "setup",
  "POST /api/setup": "setup",
  "GET /api/projects": "self",
  "POST /api/projects": "self",
  "GET /api/projects/:id": "project:read",
  "PUT /api/projects/:id": "project:update",
  "DELETE /api/projects/:id": "project:delete",
  "POST /api/projects/:id/archive": "project:archive",
  "POST /api/projects/:id/unarchive": "project:archive",
  "GET /api/projects/:id/memberships": "member:read",
  "PUT /api/projects/:id/memberships/:userId": "member:change-role",
  "DELETE /api/projects/:id/memberships/me": "member:leave",
  "DELETE /api/projects/:id/memberships/:userId": "member:remove",
  "POST /api/projects/:id/invites": "member:invite",
  "GET /api/projects/:id/invites": "invite:read",
  "DELETE /api/projects/:id/invites/:inviteId": "member:invite",
  "GET /api/invites/:token": "public",
  "POST /api/invites/:token/accept": "public",
  "POST /api/admin/users/:userId/reset-link": "admin",
  "GET /api/auth/reset/:token": "public",
  "POST /api/auth/reset/:token": "public",
  "GET /api/projects/:id/events": "project:read",
  "GET /api/projects/:id/activity": "activity:read",
  "GET /api/projects/:id/stories": "story:read",
  "POST /api/projects/:id/stories": "story:write",
  "GET /api/projects/:id/stories/:storyId": "story:read",
  "PUT /api/projects/:id/stories/:storyId": "story:write",
  "DELETE /api/projects/:id/stories/:storyId": "story:delete",
  "POST /api/projects/:id/stories/:storyId/owners/:userId": "story:write",
  "DELETE /api/projects/:id/stories/:storyId/owners/:userId": "story:write",
  // Body-less: the actor follows/unfollows the story itself. The matrix grants a viewer this
  // write; naming another user goes through the /followers/:userId routes below instead.
  "POST /api/projects/:id/stories/:storyId/follow": "follower:write",
  "DELETE /api/projects/:id/stories/:storyId/follow": "follower:write",
  "POST /api/projects/:id/stories/:storyId/followers/:userId": "story:write",
  "DELETE /api/projects/:id/stories/:storyId/followers/:userId": "story:write",
  "GET /api/projects/:id/labels": "story:read",
  "POST /api/projects/:id/labels": "label:write",
  "PUT /api/projects/:id/labels/:labelId": "label:write",
  "DELETE /api/projects/:id/labels/:labelId": "label:delete",
  "POST /api/projects/:id/stories/:storyId/labels": "label:write",
  "DELETE /api/projects/:id/stories/:storyId/labels/:labelId": "label:write",
  "GET /api/projects/:id/iteration_overrides": "iteration:read",
  "PUT /api/projects/:id/iteration_overrides/:number": "iteration:override",
  "DELETE /api/projects/:id/iteration_overrides/:number": "iteration:override",
  "GET /api/projects/:id/epics": "story:read",
  "POST /api/projects/:id/epics": "epic:write",
  "PUT /api/projects/:id/epics/:epicId": "epic:write",
  "DELETE /api/projects/:id/epics/:epicId": "epic:delete",
  "GET /api/projects/:id/stories/:storyId/tasks": "story:read",
  "POST /api/projects/:id/stories/:storyId/tasks": "task:write",
  "PUT /api/projects/:id/stories/:storyId/tasks/:taskId": "task:write",
  "DELETE /api/projects/:id/stories/:storyId/tasks/:taskId": "task:write",
  "GET /api/projects/:id/stories/:storyId/comments": "story:read",
  "POST /api/projects/:id/stories/:storyId/comments": "comment:create",
  "PUT /api/projects/:id/stories/:storyId/comments/:commentId": "comment:update-own",
  "DELETE /api/projects/:id/stories/:storyId/comments/:commentId": "comment:delete",
  "POST /api/projects/:id/stories/:storyId/comments/:commentId/attachments": "attachment:write",
  "GET /api/projects/:id/attachments/:attachmentId": "story:read",
  "DELETE /api/projects/:id/attachments/:attachmentId": "attachment:delete",
  "GET /api/projects/:id/stories/:storyId/blockers": "story:read",
  "POST /api/projects/:id/stories/:storyId/blockers": "blocker:write",
  "PUT /api/projects/:id/stories/:storyId/blockers/:blockerId": "blocker:write",
  "DELETE /api/projects/:id/stories/:storyId/blockers/:blockerId": "blocker:write",
  "GET /api/projects/:id/review_types": "story:read",
  "POST /api/projects/:id/review_types": "review-type:write",
  "PUT /api/projects/:id/review_types/:reviewTypeId": "review-type:write",
  "GET /api/projects/:id/stories/:storyId/reviews": "story:read",
  "POST /api/projects/:id/stories/:storyId/reviews": "review:write",
  "PUT /api/projects/:id/stories/:storyId/reviews/:reviewId": "review:write",
  "DELETE /api/projects/:id/stories/:storyId/reviews/:reviewId": "review:write",
};
